[tool.poetry]
name = "rev-an-android-applaketion-angr-solver"
version = "0.1.0"
description = ""
package-mode = false

[tool.poetry.dependencies]
python = "^3.13"
angr = "^9.2.134"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
